### ISSUE TITLE
Can't associate *.org with org4idea

### ISSUE THREAD

**Issue by Trevoke** [skuro/org4idea#2] opened 2015-02-25 14:55 UTC
I'm in a new Rubymine and I can't seem to associate a .org file with the plugin anymore :/

**Comment by skuro** [comment] 2015-02-25 15:10
Is there any relevant intry in the Event Log?

**Comment by Trevoke** [comment] 2015-02-25 15:27
No, nothing in the log. An existing `x.org` file just opens as a text file, and if I create a new `y.org` it asks me what to associate it with but I don't have any option for a `.org` management.

**Comment by skuro** [comment] 2015-02-25 18:34
I just downloaded RubyMine and I could reproduce your exact behavior. Were you able to properly work with the previous version of org4idea?

**Comment by Trevoke** [comment] 2015-02-25 18:53
Yes - that's how I discovered org4idea and came to this repo in the first
place :)

**Comment by AdrieanKhisbe** [comment] 2015-03-10 10:45
Funny thing is that the same is happening to me. (while it was working with the jar I made). 
I didn't tried yet to rebuild with the exact same commit and see if it's occur too.

(I had supposed it was due because I had the homemade jar before since I hadn't seen people upsetting about)

**Comment by dephiros** [comment] 2015-07-16 21:08
I also have the same problem. Installing manually with downloaded jar file(v0.1) solve the problem. Updating v0.2 and the problem happens again

**Comment by AdrieanKhisbe** [comment] 2015-07-26 21:21
Did you try by hand installing the 0.2? (getting more clues before the hunting)

I have to admit, I didn't have that much time to dig into it lately.
(I had look at the diff, but nothing hit me. Was working locally when I made the 0.2 publication, wouldn't have published otherwise)

I'll see what I can do but I promise anything in the short term. sorry about that :/

**Comment by Trevoke** [comment] 2015-07-27 17:48
I did the following (on OSX):

1. Installed org4idea
2. Restarted Rubymine
3. Tried to create .org file => No .org extension handler available.
4. Found file in `~/Library/Application Support/Rubymine70` and copied it to `~/Downloads`
5. Uninstalled org4idea
6. Restarted Rubymine
7. Installed from disk the jar I copied
8. Restarted Rubymine
9. Tried to create .org file => No .org extension handler available.

I can email you that `jar` file if you want.


Can I download a jar for 0.2 other than the way I did it?

**Comment by skuro** [comment] 2015-07-28 07:25
@Trevoke not really, I think the issue is really there, but so far I couldn't find anything wrong in the code.

@dephiros what IDE are you using, you also on RubiMine or IDEA?

**Comment by dephiros** [comment] 2015-07-28 17:43
I am using PHPStorm

**Comment by AdrieanKhisbe** [comment] 2015-11-11 09:43
Hey @all! 
Sorry for that last answer, didn't have much opportunity to dug on this.

I don't know if it's jetbrain teams that had rebuild the package, but when I installed the plugin today for new version of Rubymine and Webstorm, upgrading/or installing the org4Idea module. 
It was working right away.

What about you?
- Has problem solve itself? 
- Otherwise try to reinstall, and tell me how it goes.
  If it's okey for everyone, I will mark the issue as (*mysteriously*) resolved.

**Comment by skuro** [comment] 2015-11-11 10:50
I will try again, but there's little to no chance that the package was rebuilt I think (no pushes / code changes since long time now). I will try again (need to experiment with IDEA 15 anyway) and comment here with my findings.

**Comment by AdrieanKhisbe** [comment] 2015-11-20 07:36
Hey @skuro, did you had the opportunity to try?
I made sevral fresh install on different os with new versions of  Rubymine, Intellij and Webstorm, 
and was working each time.

**Comment by skuro** [comment] 2015-11-21 10:42
I tried with IntelliJ IDEA v14 and v15, and I couldn't reproduce the issue. I'm currently downloading RubyMine v8 and WebStorm v11 to see whether it's any different there.

**Comment by AdrieanKhisbe** [comment] 2015-11-21 10:43
Okey, I close the issue. Reopen it if you find anything :)

**Closed by AdrieanKhisbe** 2015-11-21 10:43 UTC
Labels: bug

**Comment by skuro** [comment] 2015-11-21 13:38
Gave it a shot with fresh installs of RubyMine and WebStorm, no issues were found

**Comment by AdrieanKhisbe** [comment] 2015-11-21 13:47
that will remain a mistery :)
